"""producto deshabilitado_por_stock

Revision ID: 6ac7f727bb63
Revises: e6611738e6a8
Create Date: 2026-06-16 18:44:34.993535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ac7f727bb63'
down_revision: Union[str, None] = 'e6611738e6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estado_pedido', ['codigo'])
    op.add_column('producto', sa.Column('deshabilitado_por_stock', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'deshabilitado_por_stock')
    op.drop_constraint(None, 'estado_pedido', type_='unique')
    # ### end Alembic commands ###
