"""initial schema v7

Revision ID: 8ff5ea5987af
Revises: 
Create Date: 2026-06-16 17:25:35.933253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ff5ea5987af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_pedido',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.Column('permite_cancelar', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('orden')
    )
    op.create_table('forma_pago',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ingrediente',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.CheckConstraint('stock_cantidad >= 0', name='ck_ingrediente_stock_no_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_codigo'), 'rol', ['codigo'], unique=True)
    op.create_table('unidad_medida',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('simbolo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('direccion_entrega',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('linea1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linea2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direccion_entrega_usuario_id'), 'direccion_entrega', ['usuario_id'], unique=False)
    op.create_table('producto',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagenes_url', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('unidad_venta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidad_venta_id'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_token',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_usuario_id'), 'refresh_token', ['usuario_id'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_rol_expires_at'), 'usuario_rol', ['expires_at'], unique=False)
    op.create_index(op.f('ix_usuario_rol_rol_id'), 'usuario_rol', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuario_rol_usuario_id'), 'usuario_rol', ['usuario_id'], unique=False)
    op.create_table('pedido',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('estado_pedido_codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forma_pago_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_entrega', sa.Enum('DELIVERY', 'RETIRO_LOCAL', name='modalidadentrega'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('forma_pago_snap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion_snap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp_preference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp_payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion_entrega.id'], ),
    sa.ForeignKeyConstraint(['estado_pedido_codigo'], ['estado_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['forma_pago.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_direccion_id'), 'pedido', ['direccion_id'], unique=False)
    op.create_index(op.f('ix_pedido_estado_pedido_codigo'), 'pedido', ['estado_pedido_codigo'], unique=False)
    op.create_index(op.f('ix_pedido_forma_pago_id'), 'pedido', ['forma_pago_id'], unique=False)
    op.create_index(op.f('ix_pedido_idempotency_key'), 'pedido', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_pedido_modalidad_entrega'), 'pedido', ['modalidad_entrega'], unique=False)
    op.create_index(op.f('ix_pedido_usuario_id'), 'pedido', ['usuario_id'], unique=False)
    op.create_table('producto_ingrediente',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=True),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    op.create_table('productocategoria',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('detalle_pedido',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('nombre_snap', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('precio_unit_snap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_snap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('personalizacion', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_cantidad_positiva'),
    sa.CheckConstraint('precio_unit_snap >= 0', name='check_precio_unit_snap_no_negativo'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pedido_id', 'producto_id')
    )
    op.create_index(op.f('ix_detalle_pedido_pedido_id'), 'detalle_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_detalle_pedido_producto_id'), 'detalle_pedido', ['producto_id'], unique=False)
    op.create_table('historialestadopedido',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_nuevo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['estado_anterior'], ['estado_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['estado_nuevo'], ['estado_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historialestadopedido_estado_anterior'), 'historialestadopedido', ['estado_anterior'], unique=False)
    op.create_index(op.f('ix_historialestadopedido_estado_nuevo'), 'historialestadopedido', ['estado_nuevo'], unique=False)
    op.create_index(op.f('ix_historialestadopedido_pedido_id'), 'historialestadopedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_historialestadopedido_usuario_id'), 'historialestadopedido', ['usuario_id'], unique=False)
    op.create_table('pago',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('mp_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp_status_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_idempotency_key'), 'pago', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_pago_pedido_id'), 'pago', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_pedido_id'), table_name='pago')
    op.drop_index(op.f('ix_pago_idempotency_key'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_historialestadopedido_usuario_id'), table_name='historialestadopedido')
    op.drop_index(op.f('ix_historialestadopedido_pedido_id'), table_name='historialestadopedido')
    op.drop_index(op.f('ix_historialestadopedido_estado_nuevo'), table_name='historialestadopedido')
    op.drop_index(op.f('ix_historialestadopedido_estado_anterior'), table_name='historialestadopedido')
    op.drop_table('historialestadopedido')
    op.drop_index(op.f('ix_detalle_pedido_producto_id'), table_name='detalle_pedido')
    op.drop_index(op.f('ix_detalle_pedido_pedido_id'), table_name='detalle_pedido')
    op.drop_table('detalle_pedido')
    op.drop_table('productocategoria')
    op.drop_table('producto_ingrediente')
    op.drop_index(op.f('ix_pedido_usuario_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_modalidad_entrega'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_idempotency_key'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_forma_pago_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_estado_pedido_codigo'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_direccion_id'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_usuario_rol_usuario_id'), table_name='usuario_rol')
    op.drop_index(op.f('ix_usuario_rol_rol_id'), table_name='usuario_rol')
    op.drop_index(op.f('ix_usuario_rol_expires_at'), table_name='usuario_rol')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_refresh_token_usuario_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('producto')
    op.drop_index(op.f('ix_direccion_entrega_usuario_id'), table_name='direccion_entrega')
    op.drop_table('direccion_entrega')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('unidad_medida')
    op.drop_index(op.f('ix_rol_codigo'), table_name='rol')
    op.drop_table('rol')
    op.drop_table('ingrediente')
    op.drop_table('forma_pago')
    op.drop_table('estado_pedido')
    op.drop_table('categoria')
    # ### end Alembic commands ###
